:bug: Fix bug in service name
nelkor/passcryptum pull request #120
Opened 2023-05-18 08:15 UTC by VladislavBobyrev

2023-05-18 09:04 UTC, VladislavBobyrev commented on src/app/style/helpers.scss
> +  min-width: 1.4rem;
Для того чтобы кнопка не уменьшалась, если название сервиса длинное и дошло до кнопки оно начинает двигать кнопку вправо а так как ей двигаться некуда она уменьшается

2023-05-18 10:10 UTC, nelkor commented on src/app/style/helpers.scss
> +  min-width: 1.4rem;
Чтобы кнопка не уменьшалась, лучше воспользоваться правилом, запрещающим кнопке уменьшаться от соседства с элементами, расширяющимися по правилам flex. Это правило выглядит так: `flex: none`. [Статья](https://developer.mozilla.org/ru/docs/Web/CSS/flex#%D1%81%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%D0%B8%D1%81).

2023-05-19 09:10 UTC, nelkor requested changes
Auto CI has failed.

2023-05-19 10:00 UTC, nelkor approved these changes

2023-05-19 10:01 UTC, merged