:bug: Fix bug in mobile browsers
nelkor/passcryptum pull request #152
Opened 2023-07-02 11:35 UTC by VladislavBobyrev

2023-07-02 16:48 UTC, nelkor requested changes
Кажется, что решение очень хорошее, но перед тем, как его тестировать, хотелось бы, чтобы код был приведён к нужному стилю.

2023-07-02 16:48 UTC, nelkor commented on src/app/common/normalizeWH.ts
Во-первых, не "wh", а "vh". Во-вторых, файлы называются в snake-case, то есть `normalize-vh.ts`. Но такое название не соответствует тому, что делает функция. Функция следит за высотой. Значит, она должна называться `watchHeight`, а файл, соответственно — `watch-height.ts`.

2023-07-02 16:48 UTC, nelkor commented on src/app/common/normalizeWH.ts
> +export function normalize100vh() {
Мы не используем ключевое слово `function`.

```suggestion
export const watchHeight() {
```

2023-07-02 16:48 UTC, nelkor commented on src/app/common/normalizeWH.ts
> + */
Наверное, можно обойтись без комментария)

```suggestion
```

2023-07-02 16:48 UTC, nelkor commented on src/app/common/normalizeWH.ts
> +    // --vh использовать в css -> height: calc(var(--vh) * 100);
Такие комментарии выбиваются из стиля кода этого репозитория.

```suggestion
    const vh = window.innerHeight * 0.01

    document.documentElement.style.setProperty('--vh', `${vh}px`)
```

2023-07-04 09:07 UTC, VladislavBobyrev commented on src/app/common/normalizeWH.ts
спасибо, хорошее замечание

2023-07-04 10:41 UTC, nelkor requested changes
Нужны небольшие правки, связанные со структурой файлов и директорий.

2023-07-04 10:41 UTC, nelkor commented on src/app/common/index.ts
Это лишний файл. Ре-экспорт делается из слайса, но не из сегмента. В принципе, из сегмента тоже можно, но для этого нужна какая-то особая причина.

2023-07-04 10:41 UTC, nelkor commented on src/app/common/watch-height.ts
Файлы с обычными функциями слайса у нас, по традиции, лежат в сегменте `lib`. Предлагаю здесь использовать такое же название вместо `common`, чтобы не выбивалось.

2023-07-04 10:41 UTC, nelkor commented on src/app/style/global.scss
Все файлы в этом сегменте глобальные, так что название `global.scss` не подходит. Либо в `normalize.scss` это можно добавить, либо в `helpers.scss`.

2023-07-04 10:44 UTC, VladislavBobyrev commented on src/app/common/index.ts
удалил

2023-07-04 10:44 UTC, VladislavBobyrev commented on src/app/common/watch-height.ts
переименовал

2023-07-04 12:26 UTC, nelkor requested changes
Протестировал. Решение не убирает заявленную проблему.

2023-07-06 13:33 UTC, nelkor commented on src/app/lib/watch-height.ts
> +    document.documentElement.style.setProperty('--vh', `${vh.toFixed(2)}px`)
Эксперимент показал, что если не умножать на 0.01, а делить на 100, то этого бага не будет. Так что предлагаю сделать вот так:

```suggestion
    const vh = window.innerHeight / 100

    document.documentElement.style.setProperty('--vh', `${vh}px`)
```

2023-07-17 07:40 UTC, nelkor approved these changes
Супер круто! 😊

2023-07-17 07:45 UTC, merged