:microbe: Refactor Stylelint
nelkor/passcryptum pull request #17
Opened 2023-03-05 18:37 UTC by VladislavBobyrev

Убрал конфликтуюшие пакеты и для корректной обработки .scss добавил post-scss

2023-03-06 06:48 UTC, nelkor commented
Я вижу, тут убран не только пакет `stylelint`, но ещё и `stylelint-config-standard-scss`. Что с ним не так?

Проблема с устаревшими правилами осталась в том же состоянии, в каком и была.

2023-03-06 06:51 UTC, nelkor requested changes
Если добавляешь `postcss`, то хотя бы напиши причину. То же самое с удалением `stylelint-config-standard-scss`.

Если есть какие-то вопросы по Issue, то не стесняйся их обсуждать. Основная проблема со Stylelint сейчас — это использование устаревших правил.

2023-03-07 19:32 UTC, VladislavBobyrev commented
stylelint-config-standard-scss удалил по той пречине что это но делел наши правила устаревшими. После его удаления небыло предупреждений по нашеме конфигу кроме того чтобы установить postscss поэтому установил этот пакет. Зато наши правила остались  )

2023-03-08 07:04 UTC, nelkor approved these changes
Действительно, ошибку вызывали старые `node_modules`. Если переустановить их, то всё в порядке 👍

2023-03-08 07:05 UTC, merged