Create a Vue Application
nelkor/passcryptum pull request #2
Opened 2023-02-23 15:04 UTC by VladislavBobyrev

Добавил фавиконку которая понравиласть )

2023-02-24 08:56 UTC, nelkor requested changes
Иконка SVG выглядит супер!

Необходимо внести изменения в некоторые файлы, обновить версии зависимостей, убрать из PR файл `package-lock.json`, а также найти пропавший файл `vitest.config.ts`.

2023-02-24 08:56 UTC, nelkor commented on .gitignore
> +*.sw?
В сгенерированном `.gitignore` много лишнего. Предлагаю это удалить. Если что-то потом понадобится, будем добавлять по мере необходимости.

Кроме того, не хватает кое чего важного — `package-lock.json`. Существует такой подход, когда `package-lock.json` хранят в гите, но я предлагаю хранить только зависимости первого уровня.

```suggestion
node_modules
dist
.DS_Store

.idea
.vscode/*
!.vscode/extensions.json

package-lock.json
```

2023-02-24 08:56 UTC, nelkor commented on package.json
> +  "private": true,
Эти три строки совершенно ничего не привносят, они лишние. Предлагаю их удалить.

```suggestion
```

2023-02-24 08:56 UTC, nelkor commented on package.json
> +    "vue-tsc": "^1.0.12"
Причина мне не ясна, но у тебя проект инициализировался с не самыми свежими версиями пакетов. Вот взять для примера `vue`. Если сейчас зайти на [страницу пакета](https://www.npmjs.com/package/vue), то видно, что текущая версия 3.2.47 вышла уже 22 дня назад. А у тебя установлена версия 3.2.45. Со всеми другими пакетами картина примерно такая же.

Что сделать: обнови версии в этом файле, удали `node_modules` и `package-lock.json` и выполни заново команду `npm i`.

```suggestion
    "vue": "^3.2.47"
  },
  "devDependencies": {
    "@rushstack/eslint-patch": "^1.2.0",
    "@types/jsdom": "^21.1.0",
    "@types/node": "^18.14.0",
    "@vitejs/plugin-vue": "^4.0.0",
    "@vue/eslint-config-prettier": "^7.1.0",
    "@vue/eslint-config-typescript": "^11.0.2",
    "@vue/test-utils": "^2.3.0",
    "@vue/tsconfig": "^0.1.3",
    "eslint": "^8.34.0",
    "eslint-plugin-vue": "^9.9.0",
    "jsdom": "^21.1.0",
    "npm-run-all": "^4.1.5",
    "prettier": "^2.8.4",
    "typescript": "~4.7.4",
    "vite": "^4.1.3",
    "vitest": "^0.28.5",
    "vue-tsc": "^1.1.5"
```

2023-02-24 08:56 UTC, nelkor commented on package.json
> +    "lint": "eslint . --ext .vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --fix --ignore-path .gitignore"
Много лишних расширений файлов для команды `lint`. Предлагаю оставить так.

```suggestion
    "lint": "eslint . --ext .vue,.js,.cjs,.ts --fix --ignore-path .gitignore"
```

2023-02-24 08:56 UTC, nelkor commented on tsconfig.config.json
> +  "include": ["vite.config.*", "vitest.config.*", "cypress.config.*", "playwright.config.*"],
Лишнего сгенерировало.

```suggestion
  "include": ["vite.config.*", "vitest.config.*"],
```

2023-02-24 08:56 UTC, nelkor commented on tsconfig.config.json
> +  "include": ["vite.config.*", "vitest.config.*", "cypress.config.*", "playwright.config.*"],
Файл `vite.config.ts`, который подключается здесь, в ветке вижу. Файл `vitest.config.ts` отсутствует, хотя он должен быть. Видимо, он потерялся!

2023-02-24 12:43 UTC, nelkor requested changes
Отлично! Теперь осталось разобраться со стилем кода. Есть много неточностей, типа таких:

```
import { createApp } from 'vue'
import {App} from './app/index'
```

В одной строке есть пробелы внутри фигурных скобок, а в другой — нет. Чтобы не исправлять всё по одному, имеет смысл воспользоваться уже установленным инструментом — Prettier. Однако, даже Prettier не всесилен — `.gitignore` придётся исправлять вручную.

2023-02-24 12:43 UTC, nelkor commented on .gitignore
> +package-lock.json
Этот знак, похожий на "кирпич" означает "нет пустой строки в конце файла". А она нужна. Другим файлам эту строку может добавить Prettier, но `.gitignore` — особенный файл и на него Prettier не обращает внимания 😂

Так что придётся поставить вручную.

```suggestion
package-lock.json

```

2023-02-24 12:43 UTC, nelkor commented on package.json
> +    "lint": "eslint . --ext .vue,.js,.cjs,.ts --fix --ignore-path .gitignore"
Поскольку Prettier был установлен с инициализацией приложения, не лишним будет добавить команду для его запуска. И заодно сразу выполнить её. Это исправит много неточностей в стиле кода, которые есть на текущий момент.

```suggestion
    "lint": "eslint . --ext .vue,.js,.cjs,.ts --fix --ignore-path .gitignore",
    "format": "prettier . --write"
```

2023-02-24 13:15 UTC, VladislavBobyrev commented on package.json
> +    "lint": "eslint . --ext .vue,.js,.cjs,.ts --fix --ignore-path .gitignore"
@nelkor  можем добавить прекоммит-хуки в git, и перед пушем он проверит стили и отформатирует

2023-02-24 13:53 UTC, nelkor commented on package.json
> +    "lint": "eslint . --ext .vue,.js,.cjs,.ts --fix --ignore-path .gitignore"
@VladislavBobyrev, да, было бы неплохо)

2023-02-25 08:47 UTC, nelkor approved these changes

2023-02-25 08:51 UTC, merged