🏷️ Develop a configuration interface
nelkor/passcryptum pull request #29
Opened 2023-03-14 11:41 UTC by nelkor

В рамках данной задачи будет сделано:
- Разработан тип для представления конфига сервисов приложением;
- Разработан тип для сохранения конфига сервисов в JSON;
- ~~Разработаны функции-переводчики каждого типа в другой.~~

2023-03-15 07:45 UTC, nelkor commented
Функции-переводчики каждого типа в другой не будут разработаны в рамках этой задачи, потому что эта задача исключительно про типы.

2023-03-15 14:05 UTC, nelkor commented
Поскольку настройки сервиса для `CompressedConfig`, закодированные числом 5 (`101`), означают настройки по умолчанию, использование числа 5 в качестве таких настроек недопустимо.

2023-03-16 07:14 UTC, VladislavBobyrev requested changes

2023-03-16 07:14 UTC, VladislavBobyrev commented on src/entities/services-config/index.ts
Думаю что лучше не добавлять файл если он не используется.

2023-03-16 08:01 UTC, VladislavBobyrev approved these changes

2023-03-16 08:03 UTC, merged