Create window modal
nelkor/passcryptum pull request #49
Opened 2023-04-01 20:40 UTC by VladislavBobyrev

Реализовал модальное окно с необходимой логикой, думаю можно улучшить функциональность открытия и закрытия модального окна но пока не ясно как

2023-04-04 09:21 UTC, nelkor requested changes
До логики ревью не дошло, потому что слишком много очевидных ошибок Code style. В редакторе кода всё подчёркнуто красным, пытаться увидеть что-то из логики невозможно.

2023-04-04 09:21 UTC, nelkor commented on .husky/pre-commit
> +#npm run test:unit
Зачем закомментировал тесты? Разве твой код как-то затрагивает тест-кейсы?

2023-04-04 09:21 UTC, nelkor commented on src/pages/password-entry/components/PasswordEntry.vue
Этот файл не проходит проверку ESLint.

2023-04-04 09:21 UTC, nelkor commented on src/shared/lib/modal.ts
Этот файл не проходит проверку ESLint.

2023-04-04 09:21 UTC, nelkor commented on src/shared/lib/modal.ts
> +    document.querySelector('.page').classList.add('hidden')
Не обязательно искать элемент в доме каждый раз заново при вызове функции. Это плохо по нескольким причинам.

Правильно — найти все нужные элементы заранее и обращаться к ним при вызове функции.

2023-04-04 09:21 UTC, nelkor commented on src/shared/ui/modal-window/modal-window.vue
> +  <dialog class="modal" open aria-live="assertive" @keydown.esc="modalClose()">
Скобки — это вызов функции. В данном месте, как и во всех последующих, нам нужна сама функция, а не результат её вызова.

```suggestion
  <dialog class="modal" open aria-live="assertive" @keydown.esc="modalClose">
```

2023-04-04 09:21 UTC, nelkor commented on src/shared/ui/modal-window/modal-window.vue
> +    <article class="modal__article">
Многострочные элементы одного уровня должны быть отделены друг от друга отступом.

```suggestion
    </header>

    <article class="modal__article">
```

2023-04-04 09:21 UTC, nelkor commented on src/shared/ui/modal-window/modal-window.vue
Компонент Vue должен иметь имя в стиле Pascal.

2023-04-04 09:21 UTC, nelkor commented on src/shared/ui/modal-window/modal-window.vue
> +import { modal, modalClose } from '@/shared/lib/modal'
Внутри одного сегмента следует использовать относительные пути для импорта.

```suggestion
import { modal, modalClose } from '../../lib/modal'
```

2023-04-16 11:35 UTC, nelkor requested changes
Перед тем, как открывать PR для ревью, необходимо заребейзить ветку этого PR на целевую (dev).

2023-04-17 10:52 UTC, nelkor requested changes
Пока отметил все (надеюсь) мелкие ошибки. Желательно их поправить перед тем, как смотреть логику решения, чтобы они не мозолили глаза.

Кроме этих неточностей есть одна глобальная архитектурная ошибка — логика модального окна должна быть сущностью в нашем приложении. Если посмотреть примеры других сущностей, то можно увидеть, что они все устроены примерно так же, как модальное окно. А `shared` — это обезличенная вспомогательная логика.

2023-04-17 10:52 UTC, nelkor commented on src/pages/password-entry/components/PasswordEntry.vue
> +import { open } from '@/shared/lib/modal'
В `FSD` таких импортов не может быть. Импортировать можно либо из индексного файла сегмента, либо по относительному пути внутри сегмента.

Здесь мы видим импорт вообще из `pages`. Если надо импортировать что-то из нижестоящего слоя, то это делается только реэкспортом из сегмента.

2023-04-17 10:52 UTC, nelkor commented on src/pages/password-entry/components/PasswordEntry.vue
> +  <ModalWindow />
Если один блок кода занимает несколько строк, то должны быть отступы в одну пустую строку до и после него.

```suggestion
  </main>

  <ModalWindow />
```

2023-04-17 10:52 UTC, nelkor commented on src/pages/work-screen/components/WorkScreen.vue
> +import { open } from '@/shared/lib/modal'
Невозможные импорты.

2023-04-17 10:52 UTC, nelkor commented on src/pages/work-screen/components/WorkScreen.vue
> +  <ModalWindow />
Отступ.

```suggestion
  </main>

  <ModalWindow />
```

2023-04-17 10:52 UTC, nelkor commented on src/shared/lib/modal.ts
> +const title = ref('') as unknown as String
Значение, возвращаемое функцией `ref` не может быть нереактивным. Здесь явно ошибочное указание типа.

2023-04-17 10:52 UTC, nelkor commented on src/shared/lib/modal.ts
> +const triggerModal = ref() as unknown as HTMLElement | null
Похоже на какой-то костыль, его смысл не понятен.

2023-04-17 10:52 UTC, nelkor commented on src/shared/lib/modal.ts
> +  ) as HTMLElement
Здесь нет причины искать элемент в доме. Лучше сделать через [Template Refs](https://vuejs.org/guide/essentials/template-refs.html).

2023-04-17 10:52 UTC, nelkor commented on src/shared/lib/modal.ts
> +/**  Открывает доступное модальное окно c переданными параматрами, блокирую прокрутку страницы.
Орфографические ошибки. *Storm должен их подчёркивать.

2023-04-17 10:52 UTC, nelkor commented on src/shared/lib/modal.ts
> + *  @param event event
Ты описал параметр функции, но функция не реализует его.

2023-04-17 10:52 UTC, nelkor commented on src/shared/lib/modal.ts
> + *  @param  title загловок модального окна */
Тоже орфографическая ошибка.

2023-04-17 10:52 UTC, nelkor commented on src/shared/lib/modal.ts
> +  }
Не надо каждый раз при вызове функции проверять, существует ли `html`. Никуда он не денется. Достаточно проверить один раз при его поиске.

2023-04-17 10:52 UTC, nelkor commented on src/shared/lib/modal.ts
> +  modal.value.trigger = e.currentTarget as HTMLElement
Возможно, лишние костыли.

2023-04-17 10:52 UTC, nelkor commented on src/shared/lib/modal.ts
> +  }
Опять проверка в функции, существует ли `html`.

2023-04-17 10:52 UTC, nelkor commented on src/shared/lib/modal.ts
> +  focusTriggerButton()
Разнородные операции (присваивание и вызов функции) отделяем пустой строкой.

```suggestion
  open.value = false
  
  focusTriggerButton()
```

2023-04-17 10:52 UTC, nelkor commented on src/shared/styel/helpers.scss
> +}
Этот знак внизу файла означает: "файл не заканчивается пустой строкой". Он должен заканчиваться пустой строкой.

2023-04-17 10:52 UTC, nelkor commented on src/shared/ui/modal-window/modal-window.scss
> +}
Здесь тоже файл не заканчивается пустой строкой.

2023-04-17 10:52 UTC, nelkor commented on src/shared/ui/modal-window/modalWindow.vue
> +import { modal, modalClose, open, focusTrap } from '@/shared/lib/modal'
Невозможный импорт.

2023-04-17 10:52 UTC, nelkor commented on src/shared/ui/modal-window/modalWindow.vue
> +import '@/shared/styel/helpers.scss'
Невозможный импорт.

2023-04-17 10:52 UTC, nelkor commented on src/shared/ui/modal-window/modalWindow.vue
> +    :class="{ open: open }"
К сожалению, внутри шаблона линтер игнорирует это правило. Приходится следить за этим самому.

```suggestion
    :class="{ open }"
```

2023-04-17 10:52 UTC, nelkor commented on src/shared/ui/modal-window/modalWindow.vue
> +    @keydown.esc="modalClose()"
Мы не вызываем эти функции, а назначаем их обработчиками событий.

```suggestion
    @click="modalClose"
    @keydown.esc="modalClose"
```

2023-04-17 10:52 UTC, nelkor commented on src/shared/ui/modal-window/modalWindow.vue
> +        <button
Отступ у многострочного блока кода.

```suggestion
        </h3>

        <button
```

2023-04-17 10:52 UTC, nelkor commented on src/shared/ui/modal-window/modalWindow.vue
> +          @click="modalClose()"
Не вызываем функцию.

```suggestion
          @click="modalClose"
```

2023-04-17 10:52 UTC, nelkor commented on src/shared/ui/modal-window/modalWindow.vue
> +      <input
Отступы у многострочного блока кода.

```suggestion
      </header>

      <article class="modal__article">
        <component :is="modal.component" />
      </article>

      <input
```

2023-04-17 10:52 UTC, nelkor commented on src/shared/ui/modal-window/modalWindow.vue
> +        @focus="focusTrap()"
Не вызываем функцию.

```suggestion
        @focus="focusTrap"
```

2023-04-17 10:52 UTC, nelkor commented on src/shared/ui/modal-window/modalWindow.vue
Файл компонента Vue должен быть назван в Pascal case.

2023-04-22 07:35 UTC, VladislavBobyrev commented on src/shared/lib/modal.ts
> +  }
для этой ункции это первая проверка! без нее typtscript ругается

2023-04-22 07:36 UTC, VladislavBobyrev commented on src/shared/lib/modal.ts
> +  modal.value.trigger = e.currentTarget as HTMLElement
без них ошибка в TS

2023-04-22 07:38 UTC, nelkor commented on src/shared/lib/modal.ts
> +  }
Так это будет происходить каждый раз при вызове функции `modalClose`. Проверяй существование элемента `html` сразу, как только находишь его.

2023-04-22 07:40 UTC, VladislavBobyrev commented on src/shared/lib/modal.ts
> + *  @param event event
функция его принимает )

2023-04-22 08:11 UTC, VladislavBobyrev commented on src/shared/lib/modal.ts
> +const triggerModal = ref() as unknown as HTMLElement | null
без него ошибки в TS

2023-04-22 09:20 UTC, VladislavBobyrev commented on src/shared/lib/modal.ts
> +  ) as HTMLElement
когда делаю через ref, то он ровняется null и у него нет функции focus()

2023-04-22 19:55 UTC, nelkor requested changes
Отметил наиболее крупные из найденных ошибок.

2023-04-22 19:55 UTC, nelkor commented on src/entities/modal-window/index.ts
Посмотри пример индексного файла слайса: `src/features/service-management/index.ts`. А именно, как организован импорт стилей.

2023-04-22 19:55 UTC, nelkor commented on src/entities/modal-window/lib/modal.ts
> +const title = ref('') as unknown as String
Вызов функции `ref` создаёт реактивную переменную. Эта переменная будет иметь тип `Ref<T>`. Конструкция `ref('')` возвращает тип `Ref<stirng>`. Ты зачем-то костылём переделываешь этот тип на конструктор `String`. Это даже в теории не может иметь смысла. Соответственно, это ошибка.

2023-04-22 19:55 UTC, nelkor commented on src/entities/modal-window/lib/modal.ts
> + *  @param  title заголовок модального окна */
Во-первых, это лишний комментарий. Во-вторых, его тоже надо уметь правильно писать. Если открыть это в PHPStorm, то он будет почёркан. Лучше просто убрать, мы не пишем JSDoc.

```suggestion
```

2023-04-22 19:55 UTC, nelkor commented on src/entities/modal-window/lib/modal.ts
> +export const modalShow = (e: Event, component: Component, title: String) => {
То есть невозможно открыть модальное окно без `Event`?

Представим ситуацию. Когда-нибудь у нас будет автоматический выход на страницу ввода мастер-пароля, если пользователь 5 минут не проявлял активность. При этом мы захотим открыть модальное окно с текстом: "вы ничего не делали, мы вас выкинули". Какой будет `Event`?

Сейчас у нас таких ситуаций нет, но модальное окно должно быть универсальным.

2023-04-22 19:55 UTC, nelkor commented on src/entities/modal-window/lib/modal.ts
> +export const modalClose = () => {
Сейчас в проекте около 70 функций. Ты добавляешь комментарии к некоторым: "эта функция делает то-то". Далее варианты:
- У каких-то функций будет такой комментарий, а у других — не будет;
- Всем функциям мы добавим такой комментарий.

Но хороший вариант только один — не добавлять их вообще. По имени функции должно быть и так понятно, что она делает. Если функция называется `closeModal`, то единственное, чем она может заниматься — это закрывать модальное окно.

```suggestion
export const closeModal = () => {
```

2023-04-22 19:55 UTC, nelkor commented on src/entities/modal-window/lib/modal.ts
> +      console.log('html element modal.value.trigger not found or null')
Какую ценность несёт вывод этого текста в `console.log`? Такое ощущение, что никакую.

2023-04-22 19:55 UTC, nelkor commented on src/entities/modal-window/lib/modal.ts
> +  focusTriggerButton()
По правилам хорошего тона функция не должна вызываться выше, чем объявляется.

2023-04-22 19:55 UTC, nelkor commented on src/entities/modal-window/ui/ModalWindow.vue
Если посмотришь примеры других слайсов, то увидишь, что компоненты у нас располагаются в сегменте `components`.

2023-04-22 19:55 UTC, nelkor commented on src/entities/modal-window/ui/ModalWindow.vue
> +import '@/shared/styel/helpers.scss'
Глобальные стили подключаются в `app/style`.

2023-04-22 19:55 UTC, nelkor commented on src/entities/modal-window/ui/ModalWindow.vue
> +const button = ref()
```suggestion
const button = ref(null)
```

2023-04-22 19:55 UTC, nelkor commented on src/entities/modal-window/ui/ModalWindow.vue
> +        <component :is="modal.component" />
В PHPStorm эта строка подчёркивается, как ошибка. Надо подумать, как это обойти.

2023-04-22 19:55 UTC, nelkor commented on src/entities/modal-window/ui/ModalWindow.vue
> +      <article class="modal__article">
Зачем нужен класс, для которого нет стилей? Зачем нужен тег, если в нём просто находится другой тег?

2023-04-22 19:55 UTC, nelkor commented on src/pages/password-entry/components/PasswordEntry.vue
> +import { open, modalShow } from '@/entities/modal-window/index'
Импортируешь три сущности, а строки всего две. Почему тогда не три?

Во-вторых, посмотри примеры, как делаются импорты из индексных файлов. Слово `index` не используется.

2023-04-23 14:01 UTC, VladislavBobyrev commented on src/entities/modal-window/index.ts
Посмотрел, у меня так же, только в файле  /features/service-management/index.ts нет експорта vue компонента

2023-04-23 14:08 UTC, VladislavBobyrev commented on src/entities/modal-window/lib/modal.ts
> +const title = ref('') as unknown as String
если убрать то будет ошибка
Type 'String' is missing the following properties from type 'Ref<string>': value, [RefSymbol]
вот поэтому там такая конструкция

2023-04-23 14:19 UTC, VladislavBobyrev commented on src/entities/modal-window/lib/modal.ts
> +export const modalShow = (e: Event, component: Component, title: String) => {
исправил, добавил event как необязательный параметр

2023-04-23 14:20 UTC, VladislavBobyrev commented on src/entities/modal-window/lib/modal.ts
> +export const modalClose = () => {
удалил коменты

2023-04-23 14:37 UTC, VladislavBobyrev commented on src/entities/modal-window/ui/ModalWindow.vue
> +      <article class="modal__article">
это всего лишь контейнер для компонентов которые передаем, для этого контейнера мы можем задавать внутренние и внешние отступы которые будут в макете)

2023-04-24 11:58 UTC, nelkor requested changes
Не все замечания были исправлены.

2023-05-01 06:32 UTC, VladislavBobyrev commented on src/entities/modal-window/lib/modal.ts
> +      console.log('html element modal.value.trigger not found or null')
ценность в том что если в этом месте будет ошибка то ее легко вычислить

2023-05-01 11:35 UTC, nelkor requested changes
Не все замечания поправлены.

2023-05-01 12:04 UTC, nelkor requested changes
Ветка неактуальна.

2023-05-01 15:06 UTC, nelkor commented on src/entities/modal-window/lib/modal.ts
> +const triggerModal = ref() as unknown as HTMLElement
Эта переменная не нужна. Она используется только один раз и то совершенно бесполезно. Я проверил, без неё всё работает так же.

2023-05-02 06:36 UTC, VladislavBobyrev commented on src/entities/modal-window/lib/modal.ts
> +const triggerModal = ref() as unknown as HTMLElement
Действительно можно убрать переменную и записать так trigger: ref() as unknown as HTMLElement

2023-05-02 06:39 UTC, VladislavBobyrev commented on src/entities/modal-window/lib/modal.ts
> +  setTimeout(() => {
да пробовал! не работает

2023-05-02 06:46 UTC, VladislavBobyrev commented on src/pages/password-entry/components/PasswordEntry.vue
> +  <main :inert="open">
так и сделаю

2023-05-02 06:48 UTC, VladislavBobyrev commented on src/entities/modal-window/lib/modal.ts
> +    modal.value.trigger = e.currentTarget as HTMLElement
Почему с ошибкой, я хотел присвоить modal.value.trigger = e.currentTarget ! тайпскрипт не понимает этого я ему сказал что это HTMLElement

2023-05-02 07:10 UTC, nelkor commented on src/entities/modal-window/lib/modal.ts
> +    modal.value.trigger = e.currentTarget as HTMLElement
Что такое `currentTarget`?

2023-05-02 07:11 UTC, nelkor commented on src/entities/modal-window/lib/modal.ts
> +const triggerModal = ref() as unknown as HTMLElement
Да. Но в итоге всё равно придётся переделать, чтобы не было `as unknown as`.

2023-05-02 07:17 UTC, VladislavBobyrev commented on src/entities/modal-window/lib/modal.ts
> +    modal.value.trigger = e.currentTarget as HTMLElement
это должна быть кнопка по которой вызывается модальное окно, она запоминается чтобы при выходе на нее переместился фокус

2023-05-02 07:17 UTC, VladislavBobyrev commented on src/entities/modal-window/lib/modal.ts
> +const triggerModal = ref() as unknown as HTMLElement
я буду только рад) особенно когда пойму как это сделать

2023-05-02 07:23 UTC, VladislavBobyrev commented on src/app/components/App.vue
> +import '../../shared/styel/helpers.scss'
Подумал что это не глобальные стили. подключил в app

2023-05-02 07:30 UTC, VladislavBobyrev commented on src/entities/modal-window/components/ModalWindow.vue
> +        type="text"
согласен, так как этот инпут не несет никакой смысл, кроме как функционального, то эта строка лишняя

2023-05-03 15:17 UTC, nelkor requested changes
Ветка не проходит автоматический CI

2023-05-04 04:22 UTC, closed without merging