:memo: Update documentation.
nelkor/passcryptum pull request #6
Opened 2023-02-25 11:46 UTC by VladislavBobyrev

Добавил описание и стилизовал readme

2023-02-25 14:48 UTC, nelkor requested changes
Стили не работают. По крайней мере, в GitHub. Форматирование файла не соответствует правилам Prettier. И ещё несколько небольших недочётов.

2023-02-25 14:48 UTC, nelkor commented on README.md
> +<h1 style='color: lightgreen'>Passcryptum  🔑</h1>
Почему два пробела перед ключом? Почему тэг `h1` со стилем, если этот стиль не работает?

```suggestion
# Passcryptum 🔑
```

2023-02-25 14:48 UTC, nelkor commented on README.md
> +🔲 логин
Почему где-то галочки, а где-то белые квадраты?

2023-02-25 14:48 UTC, nelkor commented on README.md
> +
Тут две строки отступа. Это противоречит правилам Prettier. Можно выполнить `npm run format`, чтобы Prettier исправил все свои замечания к этому файлу.

2023-02-25 14:48 UTC, nelkor commented on README.md
> +###  Для организации кода используем методологию [<span style='color: pink'>Feature-Sliced Design </span>](https://feature-sliced.design/ru) .
Пробел перед точкой. И это не заголовок, а текст. Эти стили не работают.

```suggestion
Для организации кода используем методологию [Feature-Sliced Design](https://feature-sliced.design/ru).
```

2023-02-25 14:48 UTC, nelkor commented on README.md
> +### При разработке вёрстки мы придерживаемся методологии [<span style='color: pink'>BEM</span>](https://ru.bem.info/methodology/).
Это не заголовок, а текст. Эти стили не работают.

```suggestion
При разработке вёрстки мы придерживаемся методологии [BEM](https://ru.bem.info/methodology).
```

2023-02-25 14:48 UTC, nelkor commented on README.md
> + <summary style='color: yellowgreen'>📚 Справочник Feature-Sliced Design</summary>
Эти стили не работают. Это можно сделать заголовком по желанию.

```suggestion
 ### 📚 Справочник Feature-Sliced Design
```

2023-02-25 14:48 UTC, nelkor commented on README.md
> +  <summary style='color: yellowgreen'>📚 Справочник BEM</summary>
Эти стили не работают. Это можно сделать заголовком по желанию.

```suggestion
  ### 📚 Справочник BEM
```

2023-02-25 14:48 UTC, nelkor commented on README.md
> +<li>Блок</li>
Эта вёрстка выглядит странно. Между двумя тэгами li находится какой-то контент.

2023-02-25 14:48 UTC, nelkor commented on README.md
> +  </code>
Это лишнее.

```suggestion
```

2023-02-25 14:48 UTC, nelkor commented on README.md
> +  </code>
Это лишнее.

```suggestion
```

2023-02-25 14:56 UTC, VladislavBobyrev commented on README.md
> +<h1 style='color: lightgreen'>Passcryptum  🔑</h1>
Линтер не включал

2023-02-25 14:57 UTC, VladislavBobyrev commented on README.md
> +🔲 логин
Предлагаю такими метками помечать пункты которые реализованы а когда они ещё не сделаны ставить пустой чекбокс

2023-02-25 15:28 UTC, nelkor commented on README.md
> +🔲 логин
Это не пункты реализации, а список вещей, из который формируется пароль. Так что тут вообще галочки и квадратики неуместны.

2023-02-26 06:50 UTC, VladislavBobyrev commented on README.md
> +🔲 логин
ага я как раз думал что это пункты, тогада согласен без галочек лучше

2023-02-26 07:00 UTC, VladislavBobyrev commented on README.md
> +### При разработке вёрстки мы придерживаемся методологии [<span style='color: pink'>BEM</span>](https://ru.bem.info/methodology/).
Прелдогаю оставить стили для цвета тк в VSCode они работают и проще находить разделы. Даже с учетом того что гит не поддерживает цвета.

2023-02-26 07:31 UTC, nelkor commented on README.md
> +### При разработке вёрстки мы придерживаемся методологии [<span style='color: pink'>BEM</span>](https://ru.bem.info/methodology/).
Давай лучше сделаем так, чтобы везде выглядело +/- одинаково)

2023-02-26 08:35 UTC, nelkor requested changes
Есть ещё несколько недочётов.

2023-02-26 08:35 UTC, nelkor commented on README.md
> +  Структура полного имени элемента соответствует схеме: имя-блока**имя-элемента. Имя элемента отделяется от имени блока двумя подчеркиваниями (**).
Дело в том, что `__`, как и `**` являются структурами выделения текста в Markdown. Prettier исправляет подчёркивания на звёздочки. Вот так будет работать нормально:

```suggestion
  Структура полного имени элемента соответствует схеме: `имя-блока__имя-элемента`. Имя элемента отделяется от имени блока двумя подчеркиваниями (`__`).
```

2023-02-26 08:35 UTC, nelkor commented on README.md
> +  Модуль не должен зависеть напрямую от других модулей того же слоя или вышележаших слоев
Орфографическая ошибка.

```suggestion
  Модуль не должен зависеть напрямую от других модулей того же слоя или вышележащих слоев
```

2023-02-26 10:53 UTC, VladislavBobyrev commented on README.md
> +  Cущность, определяющая внешний вид, состояние или поведение блока либо элемента.
интересно, текст копировал с документации )

2023-02-26 10:56 UTC, VladislavBobyrev commented on README.md
> +  Структура полного имени элемента соответствует схеме: имя-блока**имя-элемента. Имя элемента отделяется от имени блока двумя подчеркиваниями (**).
не знал спасибо

2023-02-26 11:04 UTC, nelkor approved these changes

2023-02-26 11:05 UTC, merged