:sparkles: modal window
nelkor/passcryptum pull request #80
Opened 2023-05-04 06:47 UTC by VladislavBobyrev

2023-05-04 10:14 UTC, nelkor requested changes
И ещё несколько багов.

Открыл окно, сразу жму Esc — он не работает.

Закрываю окно с клавиатуры — кнопка-триггер берётся в фокус.
Закрываю мышкой — не берётся.

2023-05-04 10:14 UTC, nelkor commented on src/entities/modal-window/components/ModalWindow.vue
> +const button = ref(null)
На текущий момент твоя проблема с типами решает вот так:

```suggestion
import { createElementRef } from '@/shared'

import { modal, closeModal, open, catchFocus } from '../lib/modal'

const button = createElementRef<HTMLButtonElement>()
```

Но создание переменных для компонента должно быть вынесено в хук этого компонента. Посмотри примеры, как это сделано в любом другом компоненте. Скорее всего, некоторый код из `/lib/modal` надо будет перенести в `/hooks/modal-window`.

2023-05-04 10:14 UTC, nelkor commented on src/entities/modal-window/lib/modal.ts
> +export const modal: ComputedRef<Modal> = computed(() => ({
Так же самая запись, но покороче.

```suggestion
export const modal = computed<Modal>(() => ({
```

2023-05-04 10:14 UTC, nelkor commented on src/entities/modal-window/lib/modal.ts
> +  modal.value.name = title
`Computed` только для чтения. Ему нельзя ничего присваивать. Странно, что это работает, видимо совпадение)

2023-05-04 10:14 UTC, nelkor commented on src/entities/modal-window/lib/modal.ts
> +    const button = modal.value.trigger as HTMLButtonElement
Зачем ты присваиваешь тип `HTMLButtonElement` полю, у которого тип `null | EventTarget`? Лучше сделай тип `null | HTMLButtonElement` сразу.

2023-05-04 10:14 UTC, nelkor commented on src/entities/modal-window/types.ts
> +export interface Modal {
Типы, которые мы создаём сами, лучше называть не менее чем в два слова. Чтобы не путать их с уже существующими.

```suggestion
export interface ModalState {
```

2023-05-06 07:02 UTC, VladislavBobyrev commented on src/entities/modal-window/lib/modal.ts
> +  modal.value.name = title
а каким образом тогда менять заголовок?

2023-05-06 09:52 UTC, nelkor commented on src/entities/modal-window/lib/modal.ts
> +  modal.value.name = title
Изменять значения можно у рефов.

2023-05-15 08:33 UTC, closed without merging